-- JAAB Collections Supabase schema
-- Run this once in Supabase Dashboard > SQL Editor.

create extension if not exists "pgcrypto";

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  name text not null,
  email text not null unique,
  role text not null default 'customer' check (role in ('customer', 'admin')),
  created_at timestamptz not null default now()
);

create table if not exists public.products (
  id text primary key,
  name text not null,
  category text not null check (category in ('Bags', 'Perfumes')),
  price integer not null check (price >= 0),
  stock integer not null default 0 check (stock >= 0),
  badge text not null default '',
  tone text not null default 'clay',
  description text not null default '',
  emoji text not null default '◒',
  image text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.orders (
  id text primary key,
  user_id uuid not null references auth.users(id) on delete restrict,
  customer text not null,
  phone text not null,
  email text not null,
  total integer not null check (total >= 0),
  status text not null default 'Order received' check (status in ('Order received', 'Processing', 'Out for delivery', 'Delivered', 'Cancelled')),
  payment text not null check (payment in ('Mobile Money', 'Pay on delivery')),
  reference text not null unique,
  address text not null,
  delivery_address jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id text not null references public.orders(id) on delete cascade,
  product_id text not null references public.products(id) on delete restrict,
  name text not null,
  quantity integer not null check (quantity > 0),
  price integer not null check (price >= 0)
);

create or replace function public.create_order(
  p_order_id text,
  p_user_id uuid,
  p_customer text,
  p_phone text,
  p_email text,
  p_payment text,
  p_address text,
  p_delivery_address jsonb,
  p_items jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_line jsonb;
  v_product public.products%rowtype;
  v_quantity integer;
  v_total integer := 0;
  v_order_items jsonb := '[]'::jsonb;
  v_order public.orders%rowtype;
  v_created_at timestamptz := now();
begin
  if coalesce(jsonb_typeof(p_items), '') <> 'array' then
    raise exception 'Order items must be a JSON array.' using errcode = '22023';
  end if;
  if jsonb_array_length(p_items) = 0 then
    raise exception 'The order must contain at least one item.' using errcode = '22023';
  end if;
  if p_payment not in ('Mobile Money', 'Pay on delivery') then
    raise exception 'Unsupported payment method.' using errcode = '22023';
  end if;

  for v_line in select value from jsonb_array_elements(p_items)
  loop
    if coalesce(v_line->>'productId', '') = '' then
      raise exception 'An order item is missing its product ID.' using errcode = '22023';
    end if;
    v_quantity := (v_line->>'quantity')::integer;
    if v_quantity < 1 then
      raise exception 'Order quantities must be positive integers.' using errcode = '22023';
    end if;

    select * into v_product
    from public.products
    where id = v_line->>'productId'
    for update;
    if not found then
      raise exception 'Product % is no longer available.', v_line->>'productId' using errcode = 'P0002';
    end if;
    if v_product.stock < v_quantity then
      raise exception 'Product % is no longer available in that quantity.', v_product.name using errcode = 'P0001';
    end if;

    update public.products set stock = stock - v_quantity where id = v_product.id;
    v_total := v_total + v_product.price * v_quantity;
    v_order_items := v_order_items || jsonb_build_array(jsonb_build_object(
      'productId', v_product.id,
      'name', v_product.name,
      'quantity', v_quantity,
      'price', v_product.price
    ));
  end loop;

  insert into public.orders (
    id, reference, user_id, customer, phone, email, total, status, payment,
    address, delivery_address, created_at
  ) values (
    p_order_id, p_order_id, p_user_id, p_customer, p_phone, p_email, v_total,
    'Order received', p_payment, p_address, p_delivery_address, v_created_at
  ) returning * into v_order;

  insert into public.order_items (order_id, product_id, name, quantity, price)
    select p_order_id, item->>'productId', item->>'name',
      (item->>'quantity')::integer, (item->>'price')::integer
    from jsonb_array_elements(v_order_items) as order_item(item);

  return jsonb_build_object(
    'id', v_order.id,
    'reference', v_order.reference,
    'userId', v_order.user_id,
    'customer', v_order.customer,
    'phone', v_order.phone,
    'email', v_order.email,
    'items', v_order_items,
    'total', v_order.total,
    'status', v_order.status,
    'payment', v_order.payment,
    'address', v_order.address,
    'deliveryAddress', v_order.delivery_address,
    'createdAt', v_order.created_at
  );
end;
$$;

revoke all on function public.create_order(text, uuid, text, text, text, text, text, jsonb, jsonb) from public, anon, authenticated;
grant execute on function public.create_order(text, uuid, text, text, text, text, text, jsonb, jsonb) to service_role;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists products_set_updated_at on public.products;
create trigger products_set_updated_at
before update on public.products
for each row execute function public.set_updated_at();

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, name, email)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'name', split_part(new.email, '@', 1)),
    new.email
  )
  on conflict (id) do update set name = excluded.name, email = excluded.email;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer set search_path = public
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and role = 'admin'
  );
$$;

alter table public.profiles enable row level security;
alter table public.products enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;

drop policy if exists "Customers can read their profile" on public.profiles;
create policy "Customers can read their profile"
on public.profiles for select
using (id = auth.uid() or public.is_admin());

drop policy if exists "Public can read products" on public.products;
create policy "Public can read products"
on public.products for select
using (true);

drop policy if exists "Admins can manage products" on public.products;
create policy "Admins can manage products"
on public.products for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Customers can read their orders" on public.orders;
create policy "Customers can read their orders"
on public.orders for select
to authenticated
using (user_id = auth.uid() or public.is_admin());

drop policy if exists "Customers can read their order items" on public.order_items;
create policy "Customers can read their order items"
on public.order_items for select
to authenticated
using (
  exists (
    select 1 from public.orders
    where orders.id = order_items.order_id
      and (orders.user_id = auth.uid() or public.is_admin())
  )
);

-- Orders should be created by the server with a service-role key or a protected RPC.
-- Do not expose a service-role key in the browser or commit it to .env.example.
revoke all on public.profiles from anon;
revoke all on public.orders from anon;
revoke all on public.order_items from anon;

notify pgrst, 'reload schema';
